-- Life Tracker: built-in exercise library (95 exercises, visible to every user).
-- Users can add their own private exercises on top of these from the app.

insert into public.exercises (name, muscle_group, kind)
values
  ('Barbell Bench Press', 'chest', 'weight_reps'),
  ('Incline Barbell Bench Press', 'chest', 'weight_reps'),
  ('Decline Bench Press', 'chest', 'weight_reps'),
  ('Dumbbell Bench Press', 'chest', 'weight_reps'),
  ('Incline Dumbbell Press', 'chest', 'weight_reps'),
  ('Dumbbell Fly', 'chest', 'weight_reps'),
  ('Cable Crossover', 'chest', 'weight_reps'),
  ('Machine Chest Press', 'chest', 'weight_reps'),
  ('Pec Deck', 'chest', 'weight_reps'),
  ('Push-Up', 'chest', 'bodyweight_reps'),
  ('Deadlift', 'back', 'weight_reps'),
  ('Barbell Row', 'back', 'weight_reps'),
  ('Pendlay Row', 'back', 'weight_reps'),
  ('Dumbbell Row', 'back', 'weight_reps'),
  ('T-Bar Row', 'back', 'weight_reps'),
  ('Lat Pulldown', 'back', 'weight_reps'),
  ('Seated Cable Row', 'back', 'weight_reps'),
  ('Machine Row', 'back', 'weight_reps'),
  ('Straight-Arm Pulldown', 'back', 'weight_reps'),
  ('Rack Pull', 'back', 'weight_reps'),
  ('Barbell Shrug', 'back', 'weight_reps'),
  ('Dumbbell Shrug', 'back', 'weight_reps'),
  ('Pull-Up', 'back', 'bodyweight_reps'),
  ('Chin-Up', 'back', 'bodyweight_reps'),
  ('Inverted Row', 'back', 'bodyweight_reps'),
  ('Back Extension', 'back', 'bodyweight_reps'),
  ('Overhead Press', 'shoulders', 'weight_reps'),
  ('Dumbbell Shoulder Press', 'shoulders', 'weight_reps'),
  ('Arnold Press', 'shoulders', 'weight_reps'),
  ('Machine Shoulder Press', 'shoulders', 'weight_reps'),
  ('Lateral Raise', 'shoulders', 'weight_reps'),
  ('Cable Lateral Raise', 'shoulders', 'weight_reps'),
  ('Front Raise', 'shoulders', 'weight_reps'),
  ('Rear Delt Fly', 'shoulders', 'weight_reps'),
  ('Face Pull', 'shoulders', 'weight_reps'),
  ('Upright Row', 'shoulders', 'weight_reps'),
  ('Barbell Curl', 'biceps', 'weight_reps'),
  ('EZ-Bar Curl', 'biceps', 'weight_reps'),
  ('Dumbbell Curl', 'biceps', 'weight_reps'),
  ('Hammer Curl', 'biceps', 'weight_reps'),
  ('Incline Dumbbell Curl', 'biceps', 'weight_reps'),
  ('Preacher Curl', 'biceps', 'weight_reps'),
  ('Cable Curl', 'biceps', 'weight_reps'),
  ('Triceps Pushdown', 'triceps', 'weight_reps'),
  ('Overhead Triceps Extension', 'triceps', 'weight_reps'),
  ('Skull Crusher', 'triceps', 'weight_reps'),
  ('Close-Grip Bench Press', 'triceps', 'weight_reps'),
  ('Triceps Kickback', 'triceps', 'weight_reps'),
  ('Dip', 'triceps', 'bodyweight_reps'),
  ('Bench Dip', 'triceps', 'bodyweight_reps'),
  ('Back Squat', 'legs', 'weight_reps'),
  ('Front Squat', 'legs', 'weight_reps'),
  ('Hack Squat', 'legs', 'weight_reps'),
  ('Goblet Squat', 'legs', 'weight_reps'),
  ('Leg Press', 'legs', 'weight_reps'),
  ('Romanian Deadlift', 'legs', 'weight_reps'),
  ('Sumo Deadlift', 'legs', 'weight_reps'),
  ('Bulgarian Split Squat', 'legs', 'weight_reps'),
  ('Walking Lunge', 'legs', 'weight_reps'),
  ('Leg Extension', 'legs', 'weight_reps'),
  ('Lying Leg Curl', 'legs', 'weight_reps'),
  ('Seated Leg Curl', 'legs', 'weight_reps'),
  ('Standing Calf Raise', 'legs', 'weight_reps'),
  ('Seated Calf Raise', 'legs', 'weight_reps'),
  ('Bodyweight Squat', 'legs', 'bodyweight_reps'),
  ('Step-Up', 'legs', 'bodyweight_reps'),
  ('Hip Thrust', 'glutes', 'weight_reps'),
  ('Glute Bridge', 'glutes', 'weight_reps'),
  ('Cable Kickback', 'glutes', 'weight_reps'),
  ('Hip Abduction Machine', 'glutes', 'weight_reps'),
  ('Cable Crunch', 'core', 'weight_reps'),
  ('Hanging Leg Raise', 'core', 'bodyweight_reps'),
  ('Ab Wheel Rollout', 'core', 'bodyweight_reps'),
  ('Crunch', 'core', 'bodyweight_reps'),
  ('Russian Twist', 'core', 'bodyweight_reps'),
  ('Dead Bug', 'core', 'bodyweight_reps'),
  ('Plank', 'core', 'duration'),
  ('Side Plank', 'core', 'duration'),
  ('Hollow Hold', 'core', 'duration'),
  ('Kettlebell Swing', 'full_body', 'weight_reps'),
  ('Power Clean', 'full_body', 'weight_reps'),
  ('Clean and Press', 'full_body', 'weight_reps'),
  ('Thruster', 'full_body', 'weight_reps'),
  ('Burpee', 'full_body', 'bodyweight_reps'),
  ('Treadmill Run', 'cardio', 'distance_time'),
  ('Outdoor Run', 'cardio', 'distance_time'),
  ('Walk', 'cardio', 'distance_time'),
  ('Stationary Bike', 'cardio', 'distance_time'),
  ('Outdoor Cycle', 'cardio', 'distance_time'),
  ('Rowing Machine', 'cardio', 'distance_time'),
  ('Elliptical', 'cardio', 'distance_time'),
  ('SkiErg', 'cardio', 'distance_time'),
  ('Swimming', 'cardio', 'distance_time'),
  ('Stair Climber', 'cardio', 'duration'),
  ('Jump Rope', 'cardio', 'duration')
on conflict do nothing;
